POST http://localhost:3000/api/likes
Content-Type: application/json

{
    "post": "6405eef1a568d8100b22ded9",
    "user": "6405d6f108f7f88911a97212",
    "type": "like"
}

###
GET http://localhost:3000/api/likes/6405eef1a568d8100b22ded9